import { ModuleDescriptor, FunctionDescriptor, ParameterDescriptor } from "./types";

const buildParams = (count: number): ParameterDescriptor[] => {
    const params: ParameterDescriptor[] = [];
    for (let i = 0; i < count; i++) {
        params.push({ name: `arg${i}`, type: "u32" });
    }
    return params;
};

const makeFunc = (name: string, argCount: number, overrides: Partial<FunctionDescriptor> = {}): FunctionDescriptor => ({
    name,
    params: overrides.params ?? buildParams(argCount),
    returnType: overrides.returnType ?? "u32",
    callingConvention: overrides.callingConvention ?? "stdcall",
});

export const advapi32Module: ModuleDescriptor = {
    name: "advapi32",
    functions: [
        makeFunc("RegOpenKeyEx", 5),
        makeFunc("RegOpenKeyExA", 5),
        makeFunc("RegOpenKeyExW", 5),
        makeFunc("RegOpenKeyA", 3),
        makeFunc("RegOpenKeyW", 3),
        makeFunc("RegOpenKeyTransactedA", 7),
        makeFunc("RegOpenKeyTransactedW", 7),
        makeFunc("RegQueryValueEx", 6),
        makeFunc("RegQueryValueExA", 6),
        makeFunc("RegQueryValueExW", 6),
        makeFunc("RegGetValueA", 7),
        makeFunc("RegGetValueW", 7),
        makeFunc("RegCloseKey", 1),
        makeFunc("RegFlushKey", 1),
        makeFunc("RegSetValueExA", 6),
        makeFunc("RegSetValueExW", 6),
        makeFunc("RegCreateKeyA", 3),
        makeFunc("RegCreateKeyW", 3),
        makeFunc("RegCreateKeyExA", 9),
        makeFunc("RegCreateKeyExW", 9),
        makeFunc("RegCreateKeyTransactedA", 11),
        makeFunc("RegCreateKeyTransactedW", 11),
        makeFunc("RegDeleteKeyA", 2),
        makeFunc("RegDeleteKeyW", 2),
        makeFunc("RegDeleteValueA", 2),
        makeFunc("RegDeleteValueW", 2),
        makeFunc("RegQueryInfoKeyA", 12),
        makeFunc("RegQueryInfoKeyW", 12),
        makeFunc("RegEnumKeyExA", 8),
        makeFunc("RegEnumKeyExW", 8),
        makeFunc("RegEnumValueA", 8),
        makeFunc("RegEnumValueW", 8),
        makeFunc("OpenSCManagerA", 3),
        makeFunc("CreateServiceA", 13),
        makeFunc("OpenServiceA", 3),
        makeFunc("CloseServiceHandle", 1),
        makeFunc("StartServiceCtrlDispatcherA", 1),
        makeFunc("RegisterServiceCtrlHandlerA", 2),
        makeFunc("SetServiceStatus", 2),
        makeFunc("GetUserNameA", 2),
        makeFunc("GetUserNameW", 2),
        makeFunc("AllocateAndInitializeSid", 11),
        makeFunc("FreeSid", 1),
        makeFunc("CheckTokenMembership", 3),
        makeFunc("InitializeAcl", 3),
        makeFunc("AddAccessAllowedAce", 4),
        makeFunc("AddAccessDeniedAce", 4),
        makeFunc("OpenProcessToken", 3),
        makeFunc("GetTokenInformation", 5),
        makeFunc("RegEnumKeyA", 4),
        makeFunc("RegQueryValueA", 4),
        makeFunc("SetNamedSecurityInfoA", 7),
        // CryptoAPI
        makeFunc("CryptAcquireContextA", 5),
        makeFunc("CryptReleaseContext", 2),
        makeFunc("CryptGenRandom", 3),
        makeFunc("CryptCreateHash", 5),
        makeFunc("CryptHashData", 4),
        makeFunc("CryptGetHashParam", 5),
        makeFunc("CryptImportKey", 6),
        makeFunc("CryptVerifySignatureA", 6),
        makeFunc("CryptDestroyHash", 1),
        makeFunc("CryptDestroyKey", 1),
        makeFunc("IsValidSid", 1),
        makeFunc("IsTextUnicode", 3),
        makeFunc("RegQueryValueW", 4),
        makeFunc("RegEnumKeyW", 4),
        makeFunc("RegDeleteKeyExA", 4),
        makeFunc("RegDeleteKeyExW", 4),
        makeFunc("RegSetValueA", 5),
        makeFunc("RegSetValueW", 5),
        makeFunc("SetNamedSecurityInfoW", 7),
        makeFunc("OpenSCManagerW", 3),
        makeFunc("OpenServiceW", 3),
        makeFunc("CryptAcquireContextW", 5),
        makeFunc("CryptVerifySignatureW", 6),
        makeFunc("LookupAccountSidA", 7),
        makeFunc("LookupAccountSidW", 7),
        makeFunc("LookupPrivilegeValueA", 3),
        makeFunc("LookupPrivilegeValueW", 3),
        makeFunc("AdjustTokenPrivileges", 6),
        makeFunc("EqualSid", 2),
        makeFunc("CopySid", 3),
        makeFunc("GetLengthSid", 1),
        makeFunc("GetSidSubAuthority", 2),
        makeFunc("GetSidSubAuthorityCount", 1),
        makeFunc("InitializeSecurityDescriptor", 2),
        makeFunc("SetSecurityDescriptorDacl", 4),

        // Auto-generated from reference signatures
        makeFunc("ConvertFiberToThread", 0),
        makeFunc("RegisterApplicationRecoveryCallback", 4),
        makeFunc("RegisterApplicationRestart", 2),
        makeFunc("RegisterEventSourceA", 2),
        makeFunc("RegisterEventSourceW", 2),
        makeFunc("RegisterWaitForSingleObject", 6),
        makeFunc("RegisterWaitForSingleObjectEx", 5),
    ]
};
