import { ModuleDescriptor, FunctionDescriptor, ParameterDescriptor } from "./types";

const buildParams = (count: number): ParameterDescriptor[] => {
    const params: ParameterDescriptor[] = [];
    for (let i = 0; i < count; i++) {
        params.push({ name: `arg${i}`, type: "u32" });
    }
    return params;
};

const makeFunc = (name: string, argCount: number, overrides: Partial<FunctionDescriptor> = {}): FunctionDescriptor => ({
    name,
    params: overrides.params ?? buildParams(argCount),
    returnType: overrides.returnType ?? "u32",
    callingConvention: overrides.callingConvention ?? "cdecl",
});

/** MSVC thiscall: callee RET N — use stdcall + stackCleanupBytes in stub generator. */
const makeThiscall = (
    name: string,
    stackCleanupBytes: number,
    overrides: Partial<FunctionDescriptor> = {},
): FunctionDescriptor => ({
    name,
    params: overrides.params ?? buildParams(stackCleanupBytes > 0 ? stackCleanupBytes / 4 : 0),
    returnType: overrides.returnType ?? "u32",
    callingConvention: "stdcall",
    stackCleanupBytes,
    ...overrides,
});

export const msvcrtModule: ModuleDescriptor = {
    name: "msvcrt",
    functions: [
        makeFunc("malloc", 1),
        makeFunc("_resetstkoflw", 0),
        makeFunc("memcpy_s", 4),
        makeFunc("_malloc_dbg", 4),
        makeFunc("_malloc", 1),
        makeFunc("??2@YAPAXI@Z", 1),
        makeFunc("@$bnew$qui", 1),
        makeFunc("free", 1),
        makeFunc("_free_dbg", 2),
        makeFunc("_free", 1),
        makeFunc("calloc", 2),
        makeFunc("_calloc_dbg", 6),
        makeFunc("_calloc", 2),
        makeFunc("realloc", 2),
        makeFunc("_realloc_dbg", 6),
        makeFunc("_realloc", 2),
        makeFunc("_strdup_dbg", 3),
        makeFunc("memset", 3),
        makeFunc("memcpy", 3),
        makeFunc("memmove", 3),
        makeFunc("strlen", 1),
        makeFunc("strcpy", 2),
        makeFunc("strncpy", 3),
        makeFunc("strcat", 2),
        makeFunc("strncat", 3),
        makeFunc("strcmp", 2),
        makeFunc("_strcmpi", 2),
        makeFunc("_stricmp", 2),
        makeFunc("_strnicmp", 3),
        makeFunc("strchr", 2),
        makeFunc("strrchr", 2),
        makeFunc("_strlwr", 1),
        makeFunc("_strdup", 1),
        makeFunc("sprintf", 16),
        makeFunc("printf", 16),
        makeFunc("sscanf", 16),
        makeFunc("atoi", 1),
        makeFunc("_atoi64", 1),
        makeFunc("atol", 1),
        makeFunc("_ltoa", 3),
        makeFunc("_ultoa", 3),
        makeFunc("srand", 1),
        makeFunc("rand", 0),
        makeFunc("time", 1),
        makeFunc("clock", 0),
        makeFunc("_sleep", 1),
        makeFunc("_ftime", 1),
        makeFunc("_errno", 0),
        makeFunc("__p__pctype", 0),
        makeFunc("__p___mb_cur_max", 0),
        makeFunc("_isctype", 2),
        makeFunc("_adjust_fdiv", 0),
        makeFunc("_initterm", 2),
        makeFunc("_ftol", 0),
        makeFunc("_chkesp", 0),
        makeFunc("_rotr", 2),
        makeFunc("_CItan", 0),
        makeFunc("_CIatan2", 0),
        makeFunc("_CIfmod", 0),
        makeFunc("ceil", 2),
        makeFunc("floor", 2),
        makeFunc("_isnan", 2),
        makeFunc("_finite", 2),
        makeFunc("atof", 1),
        makeFunc("difftime", 4),
        makeFunc("gmtime", 1),
        makeFunc("mktime", 1),
        makeFunc("_strdate", 1),
        makeFunc("_strtime", 1),
        makeFunc("_wstrdate", 1),
        makeFunc("_wstrtime", 1),
        makeFunc("wcslen", 1),
        makeFunc("wcscpy", 2),
        makeFunc("wcscat", 2),
        makeFunc("wcscmp", 2),
        makeFunc("wcsncmp", 3),
        makeFunc("wcsncpy", 3),
        makeFunc("wcschr", 2),
        makeFunc("wcsstr", 2),
        makeFunc("_wcsicmp", 2),
        makeFunc("_wcsnicmp", 3),
        makeFunc("_wcsupr", 1),
        makeFunc("_wtoi", 1),
        makeFunc("wcstoul", 3),
        makeFunc("_vsnwprintf", 4),
        makeFunc("_controlfp", 2),
        makeFunc("_control87", 2),
        makeFunc("_clearfp", 0),
        makeFunc("_onexit", 1),
        makeFunc("__dllonexit", 3),
        makeFunc("_except_handler3", 4),
        makeFunc("_XcptFilter", 2),
        makeFunc("_CrtDbgReport", 6),
        makeFunc("_CrtDbgReportW", 6),
        makeFunc("_CrtSetDbgFlag", 1),
        makeFunc("_CrtCheckMemory", 0),
        makeFunc("_CrtIsValidHeapPointer", 1),
        makeFunc("_CrtDumpMemoryLeaks", 0),
        makeFunc("_assert", 3),
        makeFunc("_wassert", 3),
        makeFunc("__CxxFrameHandler", 4),
        makeFunc("_CxxThrowException", 2),
        makeFunc("_purecall", 0),
        makeFunc("__RTDynamicCast", 5),
        makeFunc("__RTtypeid", 1),
        makeFunc("__set_app_type", 1),
        makeFunc("__p__fmode", 0),
        makeFunc("__p__commode", 0),
        makeFunc("__setusermatherr", 1),
        makeFunc("__getmainargs", 5),
        makeFunc("_acmdln", 0),
        makeFunc("_environ", 0),
        makeFunc("__environ", 0),
        makeFunc("_environ_dll", 0),
        makeFunc("?_query_new_handler@@YAP6AHI@ZXZ", 0),
        makeFunc("?_query_new_mode@@YAHXZ", 0),
        makeFunc("?_set_new_mode@@YAHH@Z", 1),
        makeFunc("?_set_new_handler@@YAP6AHI@ZP6AHI@Z@Z", 1),
        makeFunc("exit", 1),
        makeFunc("_exit", 1),
        makeFunc("_execl", 16),
        makeFunc("_execv", 2),
        makeFunc("abort", 0),
        makeFunc("?terminate@@YAXXZ", 0),
        makeThiscall("??1bad_cast@@UAE@XZ", 0),
        makeThiscall("??1type_info@@UAE@XZ", 0),
        makeThiscall("??8type_info@@QBEHABV0@@Z", 4),
        makeThiscall("?name@type_info@@QBEPBDXZ", 0),
        makeFunc("_open", 2),
        makeFunc("_sopen", 4),
        makeFunc("_close", 1),
        makeFunc("_read", 3),
        makeFunc("_write", 3),
        makeFunc("_lseek", 3),
        makeFunc("_lseeki64", 4),
        makeFunc("_tell", 1),
        makeFunc("_filelength", 1),
        makeFunc("_eof", 1),
        makeFunc("_commit", 1),
        makeFunc("_access", 2),
        makeFunc("_chmod", 2),
        makeFunc("_mkdir", 1),
        makeFunc("_rmdir", 1),
        makeFunc("_unlink", 1),
        makeFunc("_splitpath", 5),
        makeFunc("_stat", 2),
        makeFunc("_fstat", 2),
        makeFunc("_wstat", 2),
        makeFunc("_findfirst", 2),
        makeFunc("_findnext", 2),
        makeFunc("qsort", 4),
        makeFunc("getenv", 1),
        makeFunc("_putenv", 1),
        makeFunc("_wputenv", 1),
        makeFunc("_wgetenv", 1),

        // String functions missing from original list
        makeFunc("strstr", 2),
        makeFunc("strpbrk", 2),
        makeFunc("strncmp", 3),
        makeFunc("_strupr", 1),
        makeFunc("strtok", 2),
        makeFunc("memcmp", 3),

        // Conversion functions
        makeFunc("strtol", 3),
        makeFunc("strtoul", 3),
        makeFunc("strtod", 3),
        makeFunc("toupper", 1),
        makeFunc("tolower", 1),
        makeFunc("abs", 1),
        makeFunc("labs", 1),
        makeFunc("_itoa", 3),
        makeFunc("mbstowcs", 3),
        makeFunc("wcstombs", 3),
        makeFunc("wctomb", 2),
        makeFunc("setlocale", 2),

        // Formatted output
        makeFunc("_vsnprintf", 4),
        makeFunc("vsprintf", 3),
        makeFunc("_snprintf", 16),

        // Path/directory
        makeFunc("_getcwd", 2),
        makeFunc("_fullpath", 3),
        makeFunc("_makepath", 5),
        makeFunc("_chdir", 1),
        makeFunc("_setmode", 2),
        makeFunc("_fileno", 1),
        makeFunc("_isatty", 1),
        makeFunc("remove", 1),
        makeFunc("rename", 2),

        // Math (FPU intrinsics)
        makeFunc("_CIpow", 0),
        makeFunc("_CIsqrt", 0),
        makeFunc("_CIlog", 0),
        makeFunc("_CIcos", 0),
        makeFunc("_CIsin", 0),
        makeFunc("_CIexp", 0),
        makeFunc("_CIcosh", 0),
        makeFunc("_CIsinh", 0),
        makeFunc("_CItanh", 0),
        makeFunc("_fpclass", 2),
        makeFunc("_CIacos", 0),
        makeFunc("_CIasin", 0),
        makeFunc("_CIlog10", 0),
        makeFunc("sqrt", 2),
        makeFunc("pow", 4),
        makeFunc("sin", 2),
        makeFunc("cos", 2),
        makeFunc("acos", 2),
        makeFunc("asin", 2),
        makeFunc("atan", 2),
        makeFunc("atan2", 4),
        makeFunc("tan", 2),
        makeFunc("fmod", 4),
        makeFunc("fabs", 2),
        makeFunc("log", 2),
        makeFunc("log10", 2),
        makeFunc("exp", 2),
        makeFunc("ldexp", 3),
        makeFunc("frexp", 3),
        makeFunc("modf", 3),

        // Exception/runtime
        makeFunc("_beginthread", 3),
        makeFunc("_beginthreadex", 6),
        makeFunc("_endthread", 0, { returnType: "void" }),
        makeFunc("_endthreadex", 1),
        makeFunc("perror", 1, { returnType: "void" }),
        makeFunc("signal", 2),

        // High-level file I/O (FILE* based)
        makeFunc("fopen", 2),
        makeFunc("_wfopen", 2),
        makeFunc("wfopen", 2),
        makeFunc("fclose", 1),
        makeFunc("fread", 4),
        makeFunc("fwrite", 4),
        makeFunc("fgets", 3),
        makeFunc("fputs", 2),
        makeFunc("fseek", 3),
        makeFunc("ftell", 1),
        makeFunc("fflush", 1),
        makeFunc("fprintf", 16),
        makeFunc("feof", 1),
        makeFunc("ferror", 1),
        makeFunc("rewind", 1),
        makeFunc("fgetpos", 2),
        makeFunc("fsetpos", 2),
        makeFunc("fgetc", 1),
        makeFunc("getc", 1),
        makeFunc("fputc", 2),
        makeFunc("ungetc", 2),
        makeFunc("strerror", 1),

        // Character classification (individual functions)
        makeFunc("isalpha", 1),
        makeFunc("isdigit", 1),
        makeFunc("isspace", 1),
        makeFunc("isupper", 1),
        makeFunc("islower", 1),
        makeFunc("isalnum", 1),
        makeFunc("isprint", 1),
        makeFunc("ispunct", 1),
        makeFunc("iscntrl", 1),
        makeFunc("isxdigit", 1),
        makeFunc("isleadbyte", 1),
        makeFunc("iswalpha", 1),
        makeFunc("iswdigit", 1),
        makeFunc("iswpunct", 1),

        // Memory
        makeFunc("_msize", 1),
        makeFunc("_msize_dbg", 1),
        makeFunc("__msize", 1),
        makeFunc("_expand", 2),
        makeFunc("__expand", 2),
        makeFunc("_heapmin", 0),
        makeFunc("__heapmin", 0),
        makeFunc("_heapadd", 2),
        makeFunc("__heapadd", 2),
        makeFunc("_heapchk", 0),
        makeFunc("__heapchk", 0),
        makeFunc("_heapset", 1),
        makeFunc("__heapset", 1),
        makeFunc("_heapwalk", 1),
        makeFunc("__heapwalk", 1),
        makeFunc("__rtl_heapwalk", 1),
        makeFunc("_heapused", 0),
        makeFunc("__heapused", 0),
        makeFunc("?set_new_handler@@YAP6AXXZP6AXXZ@Z", 1),
        makeFunc("@set_new_handler$qpqv$v", 1),
        makeFunc("??3@YAXPAX@Z", 1),
        makeFunc("??2CObject@@SAPAXI@Z", 1),
        makeFunc("??3CObject@@SAXPAX@Z", 1),
        makeFunc("??2CObject@@SGPAXI@Z", 1),
        makeFunc("??3CObject@@SGXPAX@Z", 1),
        makeFunc("@$bnwa$qui", 1),
        makeFunc("@$bdele$qpv", 1),
        makeFunc("@$bdla$qpv", 1),

        // String formatting
        makeFunc("strftime", 4),
        makeFunc("_snwprintf", 16),
        makeFunc("swprintf", 16),

        // Console
        makeFunc("_kbhit", 0),
        makeFunc("_getch", 0),

        // CRT internal globals/helpers imported by older MSVC binaries
        makeFunc("_iob", 0),
        makeFunc("__pioinfo", 0),
        makeFunc("__badioinfo", 0),
        makeFunc("_tempnam", 2),

        // VC9 CRT (msvcr90) — exact decorated names from boot log
        makeFunc("_configthreadlocale", 1),
        makeFunc("_initterm_e", 2),
        makeFunc("_cexit", 0),
        makeFunc("_amsg_exit", 1),
        makeFunc("_crt_debugger_hook", 0),
        makeFunc("_invalid_parameter_noinfo", 0),
        makeFunc("_invoke_watson", 0),
        makeFunc("_encode_pointer", 1),
        makeFunc("_decode_pointer", 1),
        makeFunc("_lock", 1),
        makeFunc("_unlock", 1),
        makeFunc("_except_handler4_common", 6),
        makeFunc("sprintf_s", 16),
        makeFunc("_snprintf_s", 16),
        makeFunc("strncpy_s", 4),
        makeFunc("strncat_s", 4),
        makeFunc("memmove_s", 4),
        makeFunc("_time64", 1),
        makeFunc("_localtime64", 1),
        makeFunc("asctime", 1),
        makeFunc("_getdcwd", 3),
        makeFunc("_getdrive", 0),
        makeFunc("_umask", 1),
        makeFunc("_stat64i32", 2),
        makeFunc("_fstat64i32", 2),
        makeFunc("_findfirst64i32", 2),
        makeFunc("_findnext64i32", 2),
        makeFunc("_findclose", 1),
        makeFunc("_filelengthi64", 1),
        makeFunc("_ftelli64", 1),
        makeFunc("_fseeki64", 3),
        makeFunc("vfprintf", 3),
        makeFunc("fscanf", 16),
        makeFunc("setbuf", 2),
        makeFunc("_CIatan", 0),
        makeFunc("_controlfp_s", 3),
        makeFunc("memchr", 3),
        makeFunc("strcspn", 2),
        makeFunc("_gcvt", 3),
        makeFunc("_ismbblead", 1),
        makeFunc("localtime", 1),
        makeFunc("clearerr", 1),
        makeFunc("_clearerr", 1),
        makeFunc("_open_osfhandle", 2),
        makeFunc("_fdopen", 2),
        makeFunc("__doserrno", 0),
        makeFunc("_get_osfhandle", 1),
        makeFunc("__p___argc", 0),
        makeFunc("__p___argv", 0),
        makeFunc("_EH_prolog", 0),
        makeFunc("_mbctype", 0),
        makeFunc("_setmbcp", 1),
        makeFunc("_mbsnbicmp", 3),
        makeFunc("_mbsdec", 2),
        makeFunc("_ismbcspace", 1),
        makeFunc("_ismbcdigit", 1),
        makeFunc("_mbsnbcmp", 3),
        makeFunc("_mbclen", 1),
        makeFunc("_mbsrchr", 2),
        makeFunc("_mbscspn", 2),
        makeFunc("_mbsspn", 2),
        makeFunc("_mbsstr", 2),
        makeFunc("_mbsrev", 1),
        makeFunc("_mbslwr", 1),
        makeFunc("_mbsupr", 1),
        makeFunc("_mbspbrk", 2),
        makeFunc("_mbschr", 2),
        makeFunc("_mbscmp", 2),
        makeFunc("_mbsinc", 1),

        makeFunc("iswctype", 2),
        makeFunc("iswspace", 1),
        makeFunc("_setjmp3", 2),
        makeFunc("longjmp", 2),
        makeFunc("__CxxLongjmpUnwind", 1, { returnType: "void" }),
        makeFunc("??_V@YAXPAX@Z", 1),
        makeThiscall("??0exception@std@@QAE@XZ", 0),
        makeThiscall("??0exception@std@@QAE@ABQBD@Z", 4),
        makeThiscall("??0exception@std@@QAE@ABV01@@Z", 4),
        makeThiscall("??1exception@std@@UAE@XZ", 0),
        makeThiscall("??0exception@@QAE@ABQBD@Z", 4),
        makeThiscall("??0exception@@QAE@ABV0@@Z", 4),
        makeThiscall("??1exception@@UAE@XZ", 0),
        makeThiscall("?what@exception@std@@UBEPBDXZ", 0),
        makeThiscall("?_type_info_dtor_internal_method@type_info@@QAEXXZ", 0),
    ]
};
